version: '3'

services:
  backend_server:
    build: ./backend_server
    restart: unless-stopped
    environment:
      - DEV_DB_USERNAME=${DB_USERNAME}
      - DEV_DB_PASSWORD=${DB_PASSWORD}
      - DEV_DB_NAME=${DB_NAME}
      - DEV_DB_HOSTNAME=${DB_HOSTNAME}
      - DEV_DB_PORT=${DB_PORT}
      - PORT=8080
    depends_on:
      - db
    ports:
      - 8080:8080

  web_app:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./web_app:/usr/share/nginx/html
    restart: unless-stopped

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - poligonos:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  poligonos: